### ISSUE TITLE
Proven RFC-compliant datetime parser

### ISSUE THREAD

**Issue by socketpair** [cannatag/ldap3#499]
I'm too lazy for making PR. This code works for Python >= 3.2 (thanks to datetime.timezone).
This code is faster and also much more RFC compliant.

```python
import datetime
import re

qwe = re.compile(
    r'''
    ^
    (?P<Year>[0-9]{4})
    (?P<Month>0[1-9]|1[0-2])
    (?P<Day>0[1-9]|[12][0-9]|3[01])
    (?P<Hour>[01][0-9]|2[0-3])
    (?:
      (?P<Minute>[0-5][0-9])
      (?P<Second>[0-5][0-9]|60)?
    )?
    (?:
      [.,]
      (?P<Fraction>[0-9]+)
    )?  
    (?:
      Z
      |
      (?:
        (?P<Offset>[+-])
        (?P<OffHour>[01][0-9]|2[0-3])
        (?P<OffMinute>[0-5][0-9])?
      )
    )
    $
    ''',
    re.VERBOSE
)


def parse(string: str) -> datetime.datetime:
    match = qwe.fullmatch(string)
    if match is None:
        raise ValueError
    matches = match.groupdict()

    offset = datetime.timedelta(
        hours=int(matches['OffHour'] or 0),
        minutes=int(matches['OffMinute'] or 0)
    )

    if matches['Offset'] == '-':
        offset *= -1

    # Python does not support leap second in datetime (!)
    if matches['Second'] == '60':
        matches['Second'] = '59'

    # According to RFC, fraction may be applied to an Hour/Minute (!)
    fraction = float('0.' + (matches['Fraction'] or '0'))

    if matches['Minute'] is None:
        fraction *= 60
        minute = int(fraction)
        fraction -= minute
    else:
        minute = int(matches['Minute'])

    if matches['Second'] is None:
        fraction *= 60
        second = int(fraction)
        fraction -= second
    else:
        second = int(matches['Second'])

    microseconds = int(fraction * 1000000)

    return datetime.datetime(
        int(matches['Year']),
        int(matches['Month']),
        int(matches['Day']),
        int(matches['Hour']),
        minute,
        second,
        microseconds,
        datetime.timezone(offset),
    )


# 30:30.42 = 30*60 + 30.42 = 1830.42 / 3600 ~= 0.50845
print(parse('2018020215.50845Z'))
assert parse('199412161032Z') == parse('199412160532-0500')  # test from RFC
```

**Comment by cannatag** [comment]
Thanks! Will check and include it in the next release of ldap3.

Giovanni

**Comment by socketpair** [comment]
Bug - October will not be parsed. (have fixed in original message)

**Comment by cannatag** [comment]
Hi, datetime.timezone is not present in python 2.7 too. I've included your function that is used only if datetime.timezone is present otherwise the older format_time() function is used. 
Also, to be consistent with the older behaviour, I've removed the ValueError exception and return the value passed to the function in case it can't be checked.

Can you check the code in dev? Do you have any suggestion on this?

Thanks,
Giovanni

**Comment by socketpair** [comment]
1. Seems you need to write tests. At least for typical cases.
2. Do you have plans to drop Python 2 support ? Seems it is useless. Just stop Python 2 support on current release. This should clean-up you code a lot.
3. Drop support for Python < 3.4. There is no places where it can be used actually. Just drop. Do not turn your code into the mess.

**Comment by cannatag** [comment]
1. There are a lot of tests in the “tests” directory, even for the format_date() function. 
They pass for both versions now.

2. I agree with you on python2 reaching its end of life, but it is still present on most Linux boxes, so I want to keep ldap3 working on python2 too.

3. Ldap3 should work with python 3.3 and more, I know that up to version 3.2 it was slow and buggy.

**Comment by cannatag** [comment]
Added in version 2.5. 
Thanks.
