### ISSUE TITLE
Issues searching for objectGUID containing 5c

### ISSUE THREAD

**Issue by Nocturem** [cannatag/ldap3#762]
Hi having issues with searching for objectGUID's that contain 5c 

a search on filter '(objectGUID={de3f9d5f-315c-4a0a-aee9-d4bd1cbf0139})'
produces DEBUG:ldap3:PROTOCOL:SEARCH request <{'base': 'DC=**,DC=******,DC=***', 'scope': 2, 'dereferenceAlias': 3, 'sizeLimit': 0, 'timeLimit': 0, 'typesOnly': False, 'filter': '(objectGUID=\\5f\\9d\\3f\\de\\01\\4a\\ae\\e9\\d4\\bd\\1c\\bf\\01\\39)', 'attributes': ['1.1']}>

checking the hex string it should produce is 
"\\5f\\9d\\3f\\de\\5c\\31\\0a\\4a\\ae\\e9\\d4\\bd\\1c\\bf\\01\\39"

whereas a search for 
'(objectGUID={0927c506-d821-4ef6-b0ea-8737c39265fe})'
produces DEBUG:ldap3:PROTOCOL:SEARCH request <{'base': 'DC=**,DC=******,DC=net', 'scope': 2, 'dereferenceAlias': 3, 'sizeLimit': 0, 'timeLimit': 0, 'typesOnly': False, 'filter': "(objectGUID=\x06\xc5'\t!\xd8\xf6N\xb0\xea\u20217\xc3\u2019e\xfe)", 'attributes': ['1.1']}>

testing this on Version: 2.6.1

**Comment by cannatag** [comment]
This should have been fixed in 2.6.1
. Are you sure you’re using the latest version of ldap3?

**Comment by Nocturem** [comment]
Confirmed 
output from pip show

Name: ldap3
Version: 2.6.1
Summary: A strictly RFC 4510 conforming LDAP V3 pure Python client library
Home-page: https://github.com/cannatag/ldap3
Author: Giovanni Cannata
Author-email: cannatag@gmail.com
License: LGPL v3
Location: c:\users\phsv\appdata\roaming\python\python37\site-packages
Requires: pyasn1
Required-by:

**Comment by cannatag** [comment]
Hi, do you still have this issue?

**Comment by Nocturem** [comment]
Hi, apologies for the delayed response 
I can confirm that the issue is still present in 2.6.1 
To add to the complexity it appears to only be upset by the presence of 5c at certain points
'(objectGUID={f7a70f66-7604-4116-baba-4f1dd31c65cb})' - resolves fine
'(objectGUID={655ccafa-b337-4703-b8e2-cd738ee0b775})' - fails to resolve
I am guessing its not merely its presence in the string but if the specific pair is found when its split up.

**Comment by Nocturem** [comment]
found an additional issue problem with:
'(objectGUID={5197a3b2-5742-4894-a580-e0555c2d372f})' - 

this one interestingly producing an error... 

  File "...\site-packages\ldap3\protocol\convert.py", line 205, in prepare_filter_for_sending
    return bytes(ints)
ValueError: bytes must be in range(0, 256)

**Comment by cannatag** [comment]
Hi, can you try the code in dev? It should work now.

Thanks,
Giovanni

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.

**Comment by krizex** [comment]
I suppose I got the same issue again in the latest version (2.9.1).
The filter is `"(objectguid=db6ffb06-5c7e-432d-a899-7eda79866582)"` and I get the following error:
```
adagent.domains.connection Operation on LDAP connection[TMP-windows-i3i4uf5.ucc.local] failed Severity=ERROR	Traceback (most recent call last):	  File "/opt/ad-service/adagent/domains/connection.py", line 120, in get_connection	    yield conn	  File "/opt/ad-service/adagent/domains/connection.py", line 134, in get_tmp_connection	    yield c	  File "/opt/ad-service/adagent/ldap/cmd.py", line 160, in _get_connection	    yield conn	  File "/opt/ad-service/adagent/ldap/cmd.py", line 165, in search_objects    await run_in_default_executor(lambda: conn.search(args.search_base, args.s_filter, attributes=['distinguishedName']))	  File "/opt/ad-service/adagent/utils/executor.py", line 19, in run_in_default_executor	    return await run_in_executor(None, func, *args)	  File "/opt/ad-service/adagent/utils/executor.py", line 15, in run_in_executor	    return await loop.run_in_executor(executor, runner)	  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run	    result = self.fn(*self.args, **self.kwargs)	  File "/opt/ad-service/adagent/ldap/cmd.py", line 165, in <lambda>	    await run_in_default_executor(lambda: conn.search(args.search_base, args.s_filter, attributes=['distinguishedName']))	  File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 838, in search	    request = search_operation(search_base,	  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/search.py", line 371, in search_operation	    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node	  File "/usr/local/lib/python3.8/dist-packages/ldap3/operation/search.py", line 290, in compile_filter	    matching_filter['assertionValue'] = AssertionValue(prepare_filter_for_sending(filter_node.assertion['value']))  File "/usr/local/lib/python3.8/dist-packages/ldap3/protocol/convert.py", line 215, in prepare_filter_for_sending	    return bytes(ints)	ValueError: bytes must be in range(0, 256) TransactionId=cf2bcf8b-5683-40da-a68a-cbbea6680880
```

After I change the `5c` of the objectGUID to `5a` (just for random test), the filter parser did not report the error.
